from ABB import ArbolABB

arbolito = ArbolABB()
arbolito.agregar(15)
arbolito.agregar(5)
arbolito.agregar(3)
arbolito.agregar(12)
arbolito.agregar(10)
arbolito.agregar(13)
arbolito.agregar(6)
arbolito.agregar(7)
arbolito.agregar(16)
arbolito.agregar(20)
arbolito.agregar(18)
arbolito.agregar(23)

print("Pre-orden")
arbolito.preOrden(arbolito.raiz)
print("\n-------------------------------------------")
print("Post-orden")
arbolito.postOrden(arbolito.raiz)
print("\n-------------------------------------------")
print("In-orden")
arbolito.InOrden(arbolito.raiz)
arbolito.graficar(arbolito.raiz)